import { empresaLocalHandlers } from './empresaLocalHandlers.js';
import { sedeLocalHandlers } from './sedeLocalHandlers.js';
import { modulosSistemaHandlers } from './modulosSistemaHandlers.js';
import { accionesSistemaHandlers } from './accionesSistemaHandlers.js';
import { permisosHandlers } from './permisosHandlers.js';
import { rolesHandlers } from './rolesHandlers.js';
import { rolesPermisosHandlers } from './rolesPermisosHandlers.js';
import { usuariosHandlers } from './usuariosHandlers.js';
import { usuariosPermisosHandlers } from './usuariosPermisosHandlers.js';
import { categoriasProductosHandlers } from './categoriasProductosHandlers.js';
import { jornadasLaboralesHandlers } from './jornadasLaboralesHandlers.js';
import { productosHandlers } from './productosHandlers.js';
import { tiposInsumosHandlers } from './tiposInsumosHandlers.js';
import { insumosHandlers } from './insumosHandlers.js';
import { recetasHandlers } from './recetasHandlers.js';
import { clientesHandlers } from './clientesHandlers.js';
import { cotizacionesHandlers } from './cotizacionesHandlers.js';
import { estadosMesasHandlers } from './estadosMesasHandlers.js';
import { mesasHandlers } from './mesasHandlers.js';
import { tiposPedidosHandlers } from './tiposPedidosHandlers.js';
import { estadosPedidosHandlers } from './estadosPedidosHandlers.js';
import { pedidosHandlers } from './pedidosHandlers.js';
import { estadosDetallesPedidosHandlers } from './estadosDetallesPedidosHandlers.js';
import { detallesPedidosHandlers } from './detallesPedidosHandlers.js';
import { metodosPagoHandlers } from './metodosPagoHandlers.js';
import { estadosComprobantesHandlers } from './estadosComprobantesHandlers.js';
import { tiposComprobantesHandlers } from './tiposComprobantesHandlers.js';
import { comprobantesVentaHandlers } from './comprobantesVentaHandlers.js';
import { reservasHandlers } from './reservasHandlers.js';
import { inventarioMovimientosHandlers } from './inventarioMovimientosHandlers.js';
import { proveedoresHandlers } from './proveedoresHandlers.js';
import { insumosProveedoresHandlers } from './insumosProveedoresHandlers.js';
import { comprasInsumosProveedoresHandlers } from './comprasInsumosProveedoresHandlers.js';
import { tiposGastosHandlers } from './tiposGastosHandlers.js';
import { gastosHandlers } from './gastosHandlers.js';
import { cajasHandlers } from './cajasHandlers.js';
import { movimientosCajaHandlers } from './movimientosCajaHandlers.js';
import { dispositivosHandlers } from './dispositivosHandlers.js';
import { tiposReportesHandlers } from './tiposReportesHandlers.js';
import { reportesHandlers } from './reportesHandlers.js';
import { tiposNotificacionesHandlers } from './tiposNotificacionesHandlers.js';
import { notificacionesHandlers } from './notificacionesHandlers.js';
import { logsSistemaHandlers } from './logsSistemaHandlers.js';
import { inventarioHandlers } from './inventarioHandlers.js';



export function registerAllIpcHandlers() {
  empresaLocalHandlers();
  sedeLocalHandlers();
  modulosSistemaHandlers();
  accionesSistemaHandlers();
  permisosHandlers();
  rolesHandlers();
  rolesPermisosHandlers();  
  usuariosHandlers();
  usuariosPermisosHandlers();
  categoriasProductosHandlers();
  jornadasLaboralesHandlers();
  productosHandlers();
  tiposInsumosHandlers();
  insumosHandlers();
  recetasHandlers();
  clientesHandlers();
  cotizacionesHandlers();
  estadosMesasHandlers();
  mesasHandlers();
  tiposPedidosHandlers();
  estadosPedidosHandlers();
  pedidosHandlers();
  estadosDetallesPedidosHandlers();
  detallesPedidosHandlers();
  metodosPagoHandlers();
  estadosComprobantesHandlers();
  tiposComprobantesHandlers();
  comprobantesVentaHandlers();
  reservasHandlers();
  inventarioMovimientosHandlers();
  proveedoresHandlers();
  insumosProveedoresHandlers();
  comprasInsumosProveedoresHandlers();
  tiposGastosHandlers();
  gastosHandlers();
  cajasHandlers();
  movimientosCajaHandlers();
  dispositivosHandlers();
  tiposReportesHandlers();
  reportesHandlers();
  tiposNotificacionesHandlers();
  notificacionesHandlers();
  logsSistemaHandlers();
  inventarioHandlers();
} 
